# Generated by Django 5.0.3 on 2026-03-05 06:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='checkin_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian điểm danh'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='class_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='apps.classmember', verbose_name='Thành viên (class_member_id)'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='apps.attendancesession', verbose_name='Phiên điểm danh (session_id)'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Có mặt (Present)'), ('late', 'Đi trễ (Late)')], max_length=20, verbose_name='Trạng thái (status)'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='apps.class', verbose_name='Lớp học (class_id)'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo (created_by)'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Mã phiên/QR (session_token)'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='Mã lớp học'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=255, verbose_name='Tên lớp học'),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='class',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo (creator_id)'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='apps.class', verbose_name='Lớp học (class_id)'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='face_registered',
            field=models.BooleanField(default=False, verbose_name='Trạng thái đăng ký khuôn mặt'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tham gia'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng (user_id)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Nội dung bình luận'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày bình luận'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='apps.post', verbose_name='Bài viết (post_id)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận (user_id)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Tên file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(max_length=1024, verbose_name='Đường dẫn file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apps.post', verbose_name='Bài viết (post_id)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên'),
        ),
        migrations.AlterField(
            model_name='faceregistration',
            name='class_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_registration', to='apps.classmember', verbose_name='Thành viên lớp (class_member_id)'),
        ),
        migrations.AlterField(
            model_name='faceregistration',
            name='embedding_vector',
            field=models.TextField(verbose_name='Vector đặc trưng'),
        ),
        migrations.AlterField(
            model_name='faceregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng (author_id)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='apps.class', verbose_name='Lớp học (class_id)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Nội dung bài viết'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng'),
        ),
    ]
