# Generated by Django 5.0.3 on 2026-03-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file_upload',
            field=models.FileField(default='', upload_to='documents/', verbose_name='File upload thật'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Tên file hiển thị'),
        ),
    ]
