# Generated by Django 5.0.3 on 2026-04-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_customuser_created_at_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='creator_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP người tạo'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='creator_network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subnet mạng nội bộ'),
        ),
    ]
